### PR TITLE
[2189] Monitor find, publish, api healthcheck page

### PR DESCRIPTION
**Pull request by saliceti**
This will show the site as down if any dependency fails

### CODE REVIEW

**Comment by saliceti** [comment]
[Check Find and Publish healthcheck in status page](https://trello.com/c/xKxwcfTq/2189-check-find-and-publish-healthcheck-in-status-page)

**Review by cwrw — COMMENTED** [review]
Since we reinstated apply before merging this, can we also amend the health check for that as well here? as per https://github.com/DFE-Digital/teacher-services-upptime/pull/10#discussion_r666361653

**Comment by saliceti** [comment]
> Since we reinstated apply before merging this, can we also amend the health check for that as well here? as per [#10 (comment)](https://github.com/DFE-Digital/teacher-services-upptime/pull/10#discussion_r666361653)

Sure but Apply doesn't have /healthcheck. Which URL would you like?

**Comment by cwrw** [comment]
I believe it's https://www.apply-for-teacher-training.service.gov.uk/check, thanks @saliceti

**Comment by cwrw** [comment]
there's also https://www.apply-for-teacher-training.service.gov.uk/integrations/monitoring/all not sure which one is more appropriate

**Review by vigneshmsft — APPROVED** [review]

**Review by cwrw — APPROVED** [review]

**Pull request merged**
